blank_issues_enabled: false
contact_links:
  - name: Using the MMT3 issues template
    url: https://cmd-viscom.gitbook.io/portal/
    about: For a detailed explanation of how to create useful issues, visit this link.
