name: Project documentation
description: Keep track of your progression
title: "My MMT3 project"
labels: ["documentation", "good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        Nice! You've just made your first step into the world of documentation in Markdown. Let's log your progression! 
  - type: input
    id: name
    attributes:
      label: Project name
      description: In a few words, how would you describe your final work?
      placeholder: Interactive square pixels driven by Arduino
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened the past week?
      description: Also tell us, what did you expect to happen?
      placeholder: I've made progress exploring the sinus function to ...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
