name: MMT3 Project documentation
description: Keep track of your progression
title: "My MMT3 project"
labels: ["documentation", "good first issue"]
body:
  - type: markdown
    attributes:
      value: |
        Nice! You've just made your first step into the world of documentation in Markdown. Let's log your progression! 
  - type: input
    id: name
    attributes:
      label: Project name
      description: In a few words, how would you describe your final work?
      placeholder: Interactive square pixels driven by Arduino
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What do you want to create?
      description: Also tell us, where did you get your inspiration from? You can use Markdown in this field so include some links!
      placeholder: I want users to be able to tweak my visuals with my Arduino controller. I've build several sine waves that ...
    validations:
      required: true
